eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: feign-demo
  mvc:
    view:
     prefix: /WEB-INF/view/
     suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/layui?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
feign:
  hystrix:
    enabled: true
zuul:
  routes:
    api-log:
      path: /api-log/**
      serviceId: provider-demo